// Transcripts keyed by episode ID (generated by scripts/add-transcript.mjs)
// Add new transcripts by running: node scripts/add-transcript.mjs <episode-id> <transcript-file>
export const transcripts: Record<string, string> = {
  "why-your-ai-strategy-is-failing-leadership-problem-not-it": `My guest today spent nearly a decade inside one of the world's biggest mobile advertising companies,
rising from customer success manager all the way to sales chief of staff.
She was helping unify a 300-person global organization through a big merger, cutting
tens of millions in costs without losing a single pound in revenue. She then took
everything she learned about what breaks inside companies doing change and build a
business around it. She's the founder of Hacker AI, a company focused on developing and upscaling
teams in AI knowledge and helping organizations navigate the human side of AI transformation.
She also did a course on ethics of AI at the London School of Economics because she believes
how you adopt AI matters just as much as whether you adopt it at all. She's sharp,
she's direct and she has seen the insight of AI transformation in a way very few people have.
Alex, welcome to Women Lead AI podcast. As I understand you spent nearly eight years
at liftoff and you went from customer success manager to the position of chief of staff
for sales. At what point did you look at everything and felt like you want to be a
founder of your own company? What made you decide to take that leap?
I think the honest answer is I've always hated being told what to do and it's just
it's made me a very difficult employee. I think some of my old managers would probably
agree with that. It was at the back of my mind for the longest time but it's not something
maybe I was too scared to do it because jumping out and trying to do something of your own is
incredibly terrifying. You lose your paycheck, your friends or people doing the bits for you
that you don't like doing or that you're not very good at. Over the years I kept climbing
the ladder, I did an MBA and I really thought I would just keep going but I just realized
the corporate stuff never really ends the bullshit and even as a chief of staff I'd
work with a lot of C-level and and VPs they were still being told what to do you know
and it's just so it's just the only way to get out of it is really to
to jump and eventually just felt like that was the only thing I could do.
And in terms of the hacker AI, the company that you found, you were focused on training
non-technical staff. How did you decide that you know this is the specific kind of gap in
the market that you need you're going to fill? Was it a specific moment or
have you looked at it over the past two years and felt like that is something that's needed?
I would say just from my experience being in corporate before as a customer success manager so
I've always worked in AI and AI JSON fields not as a coder but working with the tools
and then working with teams who you know what I did was advertising so the people we worked with
were advertising manager and marketing managers. They couldn't care less about AI they just wanted
their campaigns to work like the hype wasn't then what it is now. But one of the issues
that we kept having was because at Lyft we built this tool that was based on machine
learning and it was really impressive but it was also a complete black box so you couldn't
look under the hood you couldn't you know and like our clients were used to like playing with
like adjusting here and there and like making tiny little tweaks to their campaigns you couldn't
do any of that and we just kept telling them oh this is the the ML the machine learning like
you can't touch it and then we ended up in a situation where one of our big clients at
some point said if you say it's the machine learning one more time I'm going to pause all
of my campaigns. So we had to kind of sit down and just think and be like okay we need to give
them something more and because they were my client I then sat down with our head of
machine learning and we devised like this workshop of how do you close the gap right
like what is machine learning he really taught me from like his point of view and his
technical point of view of like what is it that they're building and the underlying
mathematics that goes that underlines everything and that really helped me understand kind of
there's such a gap between the technology and how we want to use it in real life
and gap in language and understanding and everything else so this like training came
from that gap really and I explained to to then our client that you know these are the things
that machine learning and AI do incredibly well and you really shouldn't interfere there
and these are the things the edge case is and maybe the limits of the tool and you know
and it turns out that a lot of the intuition when they felt like something wasn't working
was actually correct they just didn't really have the language to kind of how to explain
it to us and we didn't have the language to start explaining to the technical people
um and then I did over a hundred of those talks because once the word got out that
you know that client liked it then another client liked it then another one
that really planted the seed in me that there's such a gap in language and understanding
and kind of how we view the technology from technical and non-technical people
that was back at left this was back in 2018 okay so this was ages ago and I don't think
it's really changed if anything it's got worse because now everyone is using it and the hype is
just so much right um and if you don't understand how it works and the underlying
forces I think it's really easy to believe the hype um or to fear you know the worst kind of
fear-mongering scenarios right um so that's where the seed got planted then I did an MBA
still kind of thinking I was going to be you know super corporate for the rest of my life
and I wrote my dissertation on how non-technical leaders can implement AI
into their organizations in a way that's ethical that doesn't create problems down the
line and like how can you ask the questions that you want to ask but you don't maybe
don't understand the technology fully right which I think is um yeah um and I remember actually
when I was writing in like 2020 2021 um we were talking to a bunch of different AI startups
and and organizations that were looking after ethical AI and they're like oh there's this
new startup called Open AI they're very small but you should chat to those guys um and yeah
so then that was I think that was the whole thing of just it's never really I don't feel
like that sentiment has changed right people who are technical view AI in a very particular
way and then the rest of us view it in a different way um and and people use it
really differently you know as well so that's why we focused on kind of training the teams
on just kind of getting the baseline of this is how you use your gen AI tools this is how
you can think about it this is when you should trust it this is when you shouldn't trust it
right and just get everyone on the same page and then you can really start experimenting
and coming up with like really cool crazy ideas but you need to make sure that everyone
in your team knows what they're allowed and not allowed to do how like how do you do that
considering the fact that you know I hear about a new AI tool almost every day and it feels
like you know the train that train is moving at hundreds of kilometers an hour so how can you
make sure that the teams are trained kind of it feels like they have to be trained
continuously in order to keep up with technology and also get those benefits
I don't think it's realistic to keep up to date with absolutely everything that's happening
at this point like I'm not even trying and I know from other people who are
either AI trainers or they've built a whole like creator economy around being kind of the person
that teaches you AI no one can keep up with everything that's happening so that's just
unrealistic what you can do and I mean considering that I think it's like 50%
of all VC funding now goes to AI companies which seems to be honest low to me I don't
know how anyone gets money at this point without being an AI company and I'm not
being flippant right it's just I'm sure they'll just like add it in somewhere just
so they can get the money yeah so how can you keep up with every single startup that
comes out of like that gets funded and doesn't get funded right like my LinkedIn feed is full of
SaaS startups they're all doing like slightly different things you know like my background
is kind of sales and custom success like do I know what all of them do no absolutely not
but you keep on top of the big LLMs you keep on top of the big startups that are coming out
and really getting traction and then you just have to accept that no one really knows
and things change all the time right like something that worked two months ago and that
maybe wasn't possible two months ago is possible now but I don't think you have to be the first
person to jump at every single opportunity like that and I know that controlling that feeling
of FOMO is it's hard it's hard for me I want to be you know like that's my job so I want I
need to be ahead of everything but it's just it's impossible how you know considering kind
of what you studied and the MBA that you mentioned how do you think you see the ethics
of AI differently like you because of that you were able to have that lens that a lot
of people don't have how yeah how did it make you think differently about also implementation
of it in companies and how the companies should approach it yeah the way I think about it is
you can go into ethics from like a very technical point of view right and there's all
sorts of types of biases that AI can create and a lot of it has to do with training data
or the assumptions that you make when you are building the models and all of those kind of
things I think as a non-technical person or someone who's using AI it's really unrealistic
for you to go into the hood of like every single tool so it's impossible right because
it's a lot of its proprietary information so you have to think about it in a different way
right it's if you are using these tools what's the potential fallout right and you think
of that from like a PR lens right like Anthropic got in the waters recently because
they were working with the US government right who is then working with Palantir
they have a deal where they don't I think directly work with Palantir but if they work
with the US government who works with Palantir that's fine right and it's a trade-off that
they have to make right like some people would say that's really unethical and it like
10-15 years ago would have been unthinkable for like a left-wing Silicon Valley company
to be working on military projects but in 2026 it's expected right and it's a huge chunk of
their revenues so they have to make kind of concessions or decisions somehow so the way
I think about ethics is generally think about your values don't get too hung up on the
technical aspects of like biases and everything else where I can go wrong and think of your
values right like if you value your people at the company don't replace them all with
agents at the first opportunity right and like maybe down the line that's what happens
but if you do it at the first opportunity then you know you've rode a lot of the trust that
you have with your team because then they're like well clearly people it's not what matters
most to you right you can and it might be the inevitable that that's the way things go
but you can do it in a different way right like you can start introducing agents at the same time
you train people to work with agents right like you retrain some of your workforce you give them
a lot of securities around like these are the things that we really value that humans can do
that machines can't do at this point in time and this is what we needed to focus on yes
your role is changing but your livelihood is safe for now right so there's different ways of
going about it that still protects people that focuses on your values so really I start
with that rather than any of the kind of technical aspect because you can get
like bogged down in the quagmire of like all the different types of biases and
yeah I think it's like what you said in regards to thinking what are your values is
so important because I think when you look around a lot of people they adopt these
tools right without considering what is like as a company what is most important to us like what
is our north star and I'm sure like you see that as well whereas there is like lack of that
consideration for for what is important to us right yeah and I think a lot of it doesn't
even come from a bad place I don't think there's like evil managers who are sat there
just like oh how can I create more anxiety for my teams you know it's just maybe sometimes it's
FOMO and they feel like everyone else is doing something so that's what they want to do
I think the outputs and the effects are the same but it I think a lot of time it happens
because people don't think things through not because they sit there in some evil cabal and
think about how they can like impose as much harm on other people okay so let's say I'm
a leader of a company that's has got 50 people and I want to you know I want to jump on the
train I want to implement AI like what is one of the first like questions I should be asking
myself before kind of making any any changes and any implementation I would say if you're a
leader now and you don't have any AI in your org officially and you have a 50 person org you
probably have a problem with shadow AI usage because I don't believe that no one is using
their chat gbt or Claude on the side do you want to explain what's what what is shadow AI
yeah so shadow AI is when employees use AI that like hasn't been approved by the company
right so for example I know a lot of companies that either don't use any AI or they only have
co-pilot right co-pilot at this point in time is by far the worst one of the LLMs it just has
the worst capabilities right so that's the only thing you've rolled out and yes you can block
access to chat gbt and Claude or Gemini on work laptops what you can't stop people from
doing is taking a screenshot of something on their phone putting into their chat gbt
and then getting the answer and copy pasting it right and obviously the what happens as a
result of that is then you're training open AI or Anthropic or whoever on your proprietary
company information that shouldn't really be going into those models because that data is
not siloed that's really dangerous you can't blame people for it just because it's so
you know I don't know anyone who doesn't use who's never used one of those models at this
point right it feels like productivity that you can get is just the gains are there right so it's
so much faster so how can you expect people to work in like the 19th century you know
like we don't expect people to ride a horse to work so um so you should and so I would
say that's number one if you don't have anything you more than likely have a problem
with shadow AI usage so implement something I would definitely start with kind of gen AI tools
right um like I'm agnostic I don't care where which tools companies use if they ask me for
recommendation at the moment Claude is definitely the best one it's having a moment
six months then the line that could change right six months ago I would say open AI was
probably the strongest right so you can implement Claude now but it doesn't mean that maybe at
some point you're going to have to also get chat jpt or Gemini or something else
so that would be number one and then number two and one of the mistakes I see companies
making is they kind of have this roll out and abandon approach where they give everyone
a license uh and then they go okay off you go bye um and people use it differently right
like some people are skeptics other people are early adopters and kind of experts some people
will be creating like agents and automating everything of the work others don't even know
how to prompt right so you really need to get everyone on the same baseline um that's the work
that that we do at Haka Redlich is providing that training so everyone is is there they know
how to use it and it matches with kind of your guidelines right it could be that for
example if you work with clients do you want to automate not even automate but do you want people
using um Gemini's or Claude's to write all of the emails it depends right because if suddenly
clients feel like they're talking to Claude and not their account manager that could have
rolled a lot of trust and it comes back to that training at that point right because you
can you can prompt it in a way whether you do it with kind of like voice for example
we can make really detailed prompt a will sound like you but if it sounds like you know chat jbt
generated then you know is that like is that a fault of not like having been trained it probably
is a fault of not having been trained because if people don't know what they're allowed to do
and what are what are they not allowed to do then it's it's not necessarily their fault
right i've had managers say i don't want my teams using any chat jbt to write emails
because that's what we pay them for and i think that's also unfair um again coming back to the
horse right like we don't ride a horse to work so yes we should be using it but you should
really think about the guard rails right um so if you send out an email that's a chat jbt and
i think it's also easy to get to this like lazy point where you don't really check it you
just skim it or you trust it to say what you want it to say and then it can be a
little bit off and it can especially if you're analyzing data it can really be off right like
it's just um so that's what goes into the training right of just like where do you really
sit down yes use it to create a draft which are the bits that you really have to read through
it maybe you have like a company level voice prompt or like how it's meant to sound so it
sounds as like least chat jbt ish possible um but yeah that um definitely the training
number three is the anxiety i would really address that um and it's like so in my
in my work as as a chief of staff um i was looking after like big mergers and like
post-merger integration of companies and and that's incredibly anxiety inducing for people
right they know it's coming because there's like well in my case it was two orgs that
basically looked identical and you couldn't keep it for so long but it took us a long
time to get to a place where we knew like how the roles were going to change who was going
to stay who was going to go whose management was going to go and that's you know people
were just stressing stressing for like a year while we were working on it i constantly got
questions like am i on the list you know this and that so and i don't think ai is any different
right um it's incredibly anxiety inducing and that anxiety can eat up so much of the mental
bandwidth of people so if you don't address it they could easily be spending half of their
time trying to figure out if they're going to have a job in the next year or not
that's a huge loss of productivity so i would really think about that
and and focus on that but that also means you need to have trust with your teams right because
if you just do a presentation of like oh these are the ai tools you're all safe
but you don't have trust then you've wasted everyone's time even more so how do you build
up that trust that your employees know that you're not going to let them go when
you know like anthropica whoever releases any update and suddenly can do their jobs
i think uh like what you said really rings true because in a company where um i work
you know there was a reorganization and people got laid off and you know immediately the mood
like shifts completely right and everyone is just talking about that one thing about like
who uh who was laid off who's about to get laid off and and i can imagine that with
like with ai it might be the same you know the same feeling especially when i hear that
you know that company laid off 500 people because ai can do their job right and how like
how do you make sure that people are are open to that training and like reduce that level
of anxiety comes back to trust you need to trust your leadership if you don't trust it then it's
a lot harder to do that training i think generally people understand that you can't
put the ai genie back in the bottle right like it's it's out it's it's like a tsunami
right like it's that's what our life looks like but you can reduce that
um mental bandwidth that anxiety takes by building up trust building up training right like
focusing on like i said earlier right like yes your role is changing and ai can do some of those
things but this is really what we value right like for example if you work with clients
directly maybe you go and see them more right and and you do things like um face to face
maybe you do more events so you really then focus on the relationship but you allow ai to
take over some of the kind of optimization that you would have had to do manually before
and i wonder whether like a lot of companies what they what they do is you know they get those
gains in productivity but then that means that the expectation is that you just do you're
supposed to do more work right but i think what you said in terms of like using that time
for example to have you know in person more in person meetings or create better relationships
with clients like is so important because then it feels like oh like we are using this tool
it helps us with productivity but it also means that you know and it also means that the team
actually benefits from it but on the other hand i've also seen situations where
so many tools have been released and people spend so much of their time checking the output
of the tools and fixing them and right and like i really started kind of focusing on my
linkedin about a year ago so i've created like a bunch of different projects and agents
that helped me do some of that work i find that like a year down the line some of them
don't work as well as they used to because open ai changed their models or something else
so like those things decay a lot faster than i think we're used to with like traditional
sass and tools so the upkeep that's required to keep all of those automations actually
running how you want them to run is a lot higher i think there's still a productivity
win overall but the more those automations you create then the more you have to spend
doing the upkeep so i don't think this like i don't really believe this there are some
game where we can all be on the beach and you know our agents are just like not yet
not yet well yeah um you know they're just producing everything on our behalf
i just don't see that happening at this point so like let's say that i'm in an organization
where we have co-pilot and i use it you know kind of instead of google for drafting some
emails like what but i'm i feel like i'm not a technical person i'm not you know software
engineer like what should i be doing in order to you know to to be up to date with those tools
so that you know if i were to get laid off like i have those skills and i can use them
at the like at the next company oh there's so many things you could do one thing i really
love telling people to do is you you have to approach it as like a playful thing and
experimentation i think that's the easiest way to see what works for you and where you can get
the gains and also it takes the pressure of things right of just you then don't expect
to automate all of your work within seconds but you could start with you know putting the
same prompt into different llms and see what the outputs are like right you could play
around with like a really vague prompt versus a really detailed prompt and see what the difference
in the answers that you get is and just try try and get that sense of what's working and
develop that intuition for yourself and and then pick something easy right that you could
maybe automate right so for example if you wake up every morning and you have
um a million emails that came in overnight and slack messages and something else and
something else and you have to check all of those things maybe you create some kind of like
summary email that's just just like these are the things that need your attention
and maybe that's useful right like try and create that see how that works keep testing
it to see like is it missing some things out that are important right is it leaving them out
is it working how how you want it to work if that's great that's one automation you've created
but you don't need to you know automate your whole life away i don't think that's that's the
point that i don't think you need to be you know i definitely feel that because that's probably
all the social media i consume at this point is that everything should be automated and and
i don't think that's realistic right and also it's incredibly expensive it eats up into
credits if you start automating everything then the tools kind of change right and the
outputs change and we go back to the whole like you need to upkeep all of your different
projects and automations and agents etc so just do the things that are the biggest blockers
in in your day-to-day and then see how that works out take it slow you know play around
with different tools if something doesn't work then try something differently i think also what's
incredibly useful with all of these tools like i for some reason for me learning like going into
a new like sas tool and trying to figure out like where all the buttons are and how do i
get to what i want it's just incredibly painful like i hate that i never read instructions
i just find that boring right but what one of the things with ai is you can say
this is the tool that i'm trying to use this is what i want to get to how do i do it it
doesn't always give you the right answer sometimes it can lead you down like a garden path
but in so many cases it will tell you exactly how you should do something and where all the
buttons are so it you know just keep trying to see where those opportunities are um use as
many of the tools as you can like they're not that different ultimately you can use them in
like you can learn them in a couple of weeks if you go to a different company and they
don't use copilot they use something else um but just play around with them and
yeah don't live under a rock i like what you said um in terms of using the tools like using
for example chat gbt to use a different tool like rings really true because um my dad he um
he got inspired by me when i started doing like 3d printing and he got a printer and he lives in
back in poland so you know i couldn't just kind of see what is happening so
one of our conversations were over whatsapp and you know he said at some point like oh
um i'm so glad that you know chat gbt is here otherwise i would have been asking you
like hundreds more questions so um yeah i think these tools like really
really give you that power to you know i don't know how this works and also i guess like
the kind of questions that you can ask are like sometimes you feel stupid asking someone else
but it's like your um your search history right you sometimes people are like no i don't
want others other people to see like what you know what is happening as well 100 i think
that's even more private than my google search history right it's is but but also maybe one
thing i really like doing to kind of learn and see where it's good is not focusing too much
on work but on like your personal case right like a hobby or like i've been trying to
figure out you know like i also like i love fashion content and all of those kind of things
right and then you start putting together like your body type your seasonal color analysis your
this your this and there's so many different theories i like it's overwhelming i have no
idea what i should be wearing or like i keep buying the same things over and over again in
shops so i then fed all of that information into chat and i told it you know this is
what i like i gave it also i give it pictures of like inspiration like these are the things
that like i like wearing does it suit my body type does it suit my coloring and because at this
point it knows me quite well it then tells me how to adjust some of the outfits to like
make them work for me it tells me if something is good if something isn't but but it's i
found that it's helped me develop that intuition where i go around shops now i don't want to
buy everything or the same things over and over again i'm like okay i have this these
are the gaps this is so to be honest at this point before i buy anything i put it into chat
i'm like is this what i do i need this yeah what's what's funny is now like whenever
i go like grocery shopping and we've been trying to eat healthier me and my partner
so or you know take a picture of the yogurt and what the ingredients are and ask like is
this healthy or um yeah or or not and i found one app where you can just scan the barcode
and it will give you like a score you know 73 out of 100 and if it's lower than 60 then
we're not allowed to buy it i like that right it's like it's useful for for those kind of
things right and yeah or like another thing maybe like my background is estonian russian
um so just like on a family level like we're very different political views depending on
you know what media sphere people are in and i have family who like have very different
views in the war in ukraine for example and it's really hard when because there is no like
middle ground in it really right like you're either wrong or you're right and depending
what side you're on that changes but i then use chat to kind of try and understand almost
do a conflict resolution with them and try and understand where they're coming from with their
point of view and all of these things and what i often find is the underlying that obviously to
my mind there's a lot of misinformation right and they're coming to the wrong conclusion but
the underlying fears or what they want to achieve they're all valid but we just reach
different conclusions but i i found that it's really helped me kind of mediate some of
those really tricky family dynamics that i think lots of families have in this day and age where
you can be polarized on you know on everything like the wars brexits like yeah i've actually
never had someone say it but now when i think about it like it makes so much sense to to use
it that way because you know it gives you that uh perception that and you know you can
you can kind of argue with it and tell your points versus uh versus what you know potentially
the other side things and it can give you that another perspective on on the things
especially like the the ones you mentioned so like when we think about companies and how
they're like rolling out ai like how much do you think is leadership responsible for how much
is i let's say it department responsible for and individuals like who is supposed to lead for example
on education and and you know those those things i think generally leaders think it's an it
problem or maybe like an hr like lnd you know learning and development problem
um and and they don't think it's their problem i would argue it's very much their problem from
various different points of view like their the anxiety that we talked about earlier right
of am i going to keep my job am i safe that's a leadership problem um the tools and how do
you use them what are the values like are you allowed to just like send out batch emails
to clients that you haven't looked over that's a leadership problem that's not an it problem
what kind of tools do you implement what kind of agents you build i think that's also a
leadership problem right um i think sometimes it's maybe it's laziness maybe it's like
you have so much on your mind that you don't really or you don't understand the technology
well enough and you just think especially sometimes companies have like an ai lead
or like oh they'll come up with all of the things that we need but they don't know the
intricacies of the workflows of every single team so how do you trust them to come up with
the best possible tools um i think leaders also need much more education on the possibilities
but i think the way leaders think and the way the teams think is very different i think for
the teams they need to know like how to prompt when to trust outputs when not to trust them like
when to raise an alarm uh when not to use shadow ai right like that's that for leaders
they need to be thinking much more long-term strategically if competition came along and
they built a similar company but from the ground up and they were ai native what would
they build and how would that affect us right and then i think that can really get you to
a place where you can think a little bit differently about what are the blockers
yeah 100 you know there's a lot of talk about the fact that there there is going to be a
billion dollar company just with made by a single person and i think like that's
definitely going to happen especially seeing some of the like the progress with like cloud
um so and the question that you ask like how would the company look like uh it's like it's
so interesting but then what happens if the answer is oh we would not have like this whole
department like do they do they how do you evaluate that you know risk of potentially laying
off people what from a point of view of one person
let's say a leader is thinking oh we if we were ai kind of native company like this process
that currently you know a team of 10 people is responsible for actually it can be automated
away oh yeah or we would need one or two people right yeah it's hard i think leaders who
start from the ground up with ai they don't get any of the hates then the leaders who then have
to let go their teams right but actually the outcome is in many ways the same um i think it's
a great point um there's a company in like my old field and i was in in our tech so like
advertising tech that um there's a lot of companies that use ai machine learning all those kind of
things but the technology was probably built 10 15 years ago so there's a lot of really cool
stuff that's been built that works incredibly well but the kind of the operational side or
the managing it requires hundreds and hundreds of people right and it can be clunky in many
ways um there's a company that recently kind of came about they've got a bunch of funding
and they've basically rebuilding one of the aspects of the ad tech industry but from the
ground up and ai native with all the genetic work so they're automating away a lot of the
work that would normally be done by by teams they've made a huge splash where some of the
valuations drop massively and you know and they really spook the investors um in that field
um i don't know i don't know if i have an answer like as a leader you're taught right like one
thing i you learn and if you do an mba and kind of leadership is you always have this tension
and that is leadership is managing that tension when you're being pulled in two different
directions right and i think as a leader now especially as a senior leader you will feel
the push to automate everything and introduce agents and do all of those things because otherwise
you won't have a company anymore right um but at the same time hopefully you feel the responsibility
for the teams and the people um and i don't think there is a single answer because in
different situations you would do different things but there's there's an easy way or
like there's a there are different ways of reacting to to that situation you could fire everyone
like who was it not camber carter did it right they fired like thousands of people replaced
them with agents and then they realized actually agents can't do that so now they're rehiring
them but they've destroyed a lot of trust right and in many ways i mean i'm glad they
did it because it serves as a lesson to so many other companies to not do that but that's
one way of dealing with it where they didn't think of the people but you could think of it
in a way of like okay can i give people other jobs what else could we do could we
retrain them can we do them something else um and and just go that way but i think it's
inevitable that we're all gonna have to upskill and learn new things you know we don't work
now the same way we worked during the industrial revolution and that's fine
um but it does mean that some jobs go away yeah and i think what you know what would you
say to someone you mentioned the companies are not hiring and like you can see that in
stats as well uh in in uk and in the u.s were that you know there there is a need for kind of
senior leadership but when it comes to fresh graduates actually that work can be outsourced
to ai and you know uh if let's say a law firm was hiring a new associate who would
do a lot of groundwork of research well i've got an alum that can do all of that so
if you're in the position of like recently graduating what what do you do to you know
to survive basically i don't know i it is definitely harder and i think it's only going
to get more and more harder um having said that i graduated in 2009 right in the height of the
financial crisis um and i was in a situation where me and my friends all had jobs lined up and
then those companies went bust um so they were no jobs so in a way maybe a similar situation
right i didn't graduate into an economy that was booming um what i did is i wasted a bunch of
time doing like i did a year abroad i had a lovely time i don't think it was wasted um i
learned a new language then i did something else it just took me a little bit longer to
get on the path that i wanted to get to to get into tech i also didn't know i wanted to
get into tech um and i did some kind of not so high paying jobs at much smaller companies
but eventually i got to the place where where i wanted to get to um and it ended up being
fine you know like i still got to like senior leadership levels like it's i think you feel
as a graduate that like you really have to be kind of get the job like get the promotion
like you're under so much pressure to achieve things really really fast and instantly but that's
just not how life goes all the time that's the only advice i can give really is it's you're not
the first people who have struggled to get jobs and have graduated in an economy that's
that isn't booming and you know dying to hire you um it is harder and sometimes it will
take longer yeah i relate to it because i graduated in 2020 when covet just started
right and all of the graduate schemes and all of the jobs that i was applying for
they suddenly started just sending emails out that they're not like they're stopping hiring
just because they they're not sure what's going to happen and it was that like moment
you know panic of what do i do and i did have a gap of like several months between
when i was able to find like a job that i was happy with like almost over a year um so yeah it
is it is very but you're okay now right like you got the job it just didn't happen instantly
yeah and i keep learning skills while you're looking for jobs right like maybe you start a
startup and maybe that's what a grad can do like you know there's plenty of young kind
of entrepreneurs out there who've made millions if not billions i i think you know whenever
a new technology comes in you can always think about oh like this is gonna like replace me or
this is um like it's it's gonna be a challenge or you can see it as opportunity
right and it is i i think that it is about that mindset whether you think oh you know i can
you know like i can do training for for example companies or i can become really skilled at that
one thing and you know offer it as a freelancer so um i think yeah a lot of it is about how
like how you think and how you see it whether it's it's opportunity or it's all doom and
gloom right i think so i don't i think it's attributed to winston churchill this saying but
it's like never waste the good crisis i don't know if he actually said it but i really believe
in that right um like i through my corporate career probably went through like eight restructurings
and redundancy rounds so many but i got promoted through more than half of them
and got promotions that would have never got otherwise where like i could move up not just
like from you know how they love to go send you from like your ic to suddenly you're like an
associate manager and then you become a manager and then you're an associate something else
right and they just create so many steps you can jump so many steps when there's like a
huge crisis um because the rules are different in that situation right um so yeah absolutely i
think now you know is is the easiest time to start a company um one of the main things
that companies all companies struggle with is trying to get clients and get the word out
for how they're doing and it's so easy to create content now with ai right so like half
of that and i'm not saying also made all of it away i don't think that's well you can do
it but it's not going to be very good content right but it makes it so much easier where
before would have taken someone probably a full-time role to do that you can probably
do it in a day now right so that's one day of your week that you focus on kind of marketing
and um and creating awareness and the rest of the time you focus on building the company
it is it's absolutely so many opportunities are coming from this
um and i don't think we know when you were saying you know what happens to
um employees where you know a company just like doesn't create a new department because
they're ai native from the ground up i think we're moving towards a world where we're not
going to have huge multi-corporates we will still but a lot more people will be working
for much smaller companies like five people 20 people 50 people right because you'll be able
to do what 600 people used to do with 50 people now and a few hundred of agents doing
the groundwork and when you think about you know companies implementing ai like what are
what other mistakes you mentioned one of them what mistakes do you see when the company is
rolling out uh and what not to do basically um i think a lot of them we have covered i would say
one is the kind of roll out and abandon right so when they like roll out a license and then
they just leave people to to use it however they want to um the second one
and like i feel bad saying this but if you only roll that copilot you also probably have
a shadow ai problem because people just don't like using it at the moment um so that one but
also maybe a bigger point there is just not monitoring for shadow ai usage right and having
all of your sensitive data leaked out um the trust issue right and the anxiety not addressing
that i think that's a huge mistake um and then the last one maybe is stopping at rolling out
an llm right and being like that's our ai strategy or we have like a sas that we have
for sales we have a sas that we have for ops team we have something for like our product
teams and then our engineering team uses clawed right like okay yeah that's an ai strategy but
it's a very like basic ai strategy i think um the companies that are really going to get
ahead are the ones they're not thinking how can i get a 10 improvement they're thinking how
can i get a 10x improvement and that probably means kind of thinking okay we're building this
from the ground up with a genetic ai what would we change um and where the blockers where we
relying on maybe processes that don't work uh oh another one i love this one where people
try and automate like a really fuzzy process that doesn't work or a broken process and they
try and throw ai at it um yeah that really doesn't work where do you see as like the
the biggest gap between where um a lot of companies are right now and where do you
think opportunity is when it comes to ai adoption i i would love to say we're at a place where
we all need to start thinking about like the 10x improvements in reality we're at a place
where you need to make sure that everyone in your team knows how to prompt like we're at such
basic one-on-one level and it's fine it's a really new technology
um but if we get everyone on a on a baseline and also like when to use it when not to
use it i also like i feel like almost everyone and not even in the knowledge economy i think
you know like farmers probably need to use ai right like and it just makes everyone's lives
easier when should you use it when should you not use it we all need to be up skilled on
kind of the intricacies of of this incredibly complex technical tool and technology i think uh
you know organize i think in a lot of organizations you have like basically two
groups of people where someone is like oh i'm not really a tech person i'm not you know
interested in this i'm a bit anxious about this this tech and then you have someone who is like
obsessed with it and you know every new tool they're like on it and and usually that you
know that second group is put then in charge of uh like education potentially but they're
you know they're starting with not that base knowledge but expecting everyone to be already
there um and they're like potentially they're not do you see that as well i see that um
i mean sometimes it can work it depends right but i would say in the cases where it does go
wrong maybe the people who are early adopters they don't share the same psychological fears as
the people who hold back right and i think that's where it comes from it's not like people do fall
in this curve right of like early adopters whatever is like the late majority i can't
remember where all the bits are um we treat new things differently and some people are
just naturally more skeptical but if you don't address those fears or then i mean it doesn't
matter that you show them like 10 different agents that you've built for yourself it's
if they don't want to use them because they think they're going to get lose their job
in like six months because of it it's not going to increase adoption right um so yes
i think it's good you should you should have that you should always have like um people
who are really into new tools and that help kind of create that adoption and someone that
you can always ask questions to um but would you would i put them in charge of training
the whole company probably not yeah i guess you know it comes back to that trust and how
how trusting employees employees are in the organization right whether the organization
creates an environment where saying oh like i don't understand this like can you explain
it differently that like that is absolutely fine and it is expected um but a lot of
environments are such that okay i i i got it or i'll just you know figure it out on my own
and and that's like that's very challenging it's challenging but i think it also becomes
because leaders don't really understand the technology themselves we're all just kind
of feeling around in the dark um yeah would you say that like it has to start there where
the leadership gets up skilled in it and really makes it their priority to learn because that
you know that creates that cascade where you think about use cases you think about like
how can you roll it out right yeah absolutely it's it can't be like a good ai training is
not just prompt training for your teams that's really important but that that's not really where
it should end right as the leaders you need different things you need to think about
you know can a competition create my company from the ground up with agentic ai what does
that mean um what are the downstream like if we start using um ai for hiring people right and
suddenly tells us we only need to hire white males what are the pr repercussions of that
if a journalist finds out that's a leadership problem right so understanding that there are
biases with these tools and even if you bring in a supplier um who's going to provide it
like it's still going to be ultimately your responsibility you can't always say
that it was them well why didn't you ask the right questions then right
um so there's different leaders also need to know how to prompt but it's it goes
like further beyond that of things that they need to be asking yeah like safeguards and
all of those things and where we use it like you said and where actually we shouldn't
be using it yeah how does our culture change right like how um i mean you're not gonna have
like um presents and birthday parties for the agents in your workforce but you know if people
start also doing different things do they like maybe some of them will like doing those things
right if you can spend more time with clients face to face great other people might not like
that so then they might need to do something else all of those are leadership problems
i love this conversation i like i learned so much uh i think for me the biggest takeaway was that
question that you asked like if my company was starting you know from the ground up like
what what would the competition be doing to be um if they were starting to with being ai
native um but let's do a question um a fast round of questions so um what's
uh one ai workflow or automation that you adopted and it generally you know changed how you work
mine content creation i create a lot of content on linkedin and it really helps me with that
having said that it's not fully automated i really don't believe
in full automation but that like research first draft analyzing it 100
what's the best use of ai that you've seen inside a company that most people wouldn't think
of a leadership team they started recording their meetings and they were kind of a very
established team where like there's no new blood for ages and so they worked together
quite well they started feeding those transcripts to an llm and just saying can you find holes
in our thinking and what are we missing where are we two in agreement with each other what
else should we be thinking about that is such a good use case and that's not and i'm again
i'm not saying trust it fully right but it will surface some things that you wouldn't have
thought because we all just get a bit of like inertia and set in our ways that is
that i'm gonna use that um let's say that we kind of discussed this but um i'm someone who
decides today that they're gonna lean into ai uh rather than kind of wait for guidance
um where where do i start uh so i can see you know so i can i can start today and within a
week kind of see improvement if you've never used it before let's say i've used um just chat
gbt for questions and answers i mean first my number one is make sure your prompts are good
try different prompts try a poor prompt a good prompt you know a detailed prompt see what
that the output that it gives you and i mean if you're using claude you probably have more
opportunities right now for like automation right just because it makes it easier
so then you could start like what i said earlier right like if you wake up every morning and
you have a million different emails and it's really overwhelming try and automate that
start with something small where you can create an automation right if your company doesn't allow
it and you have no ai or you have only like ai that like you can't build like little agents
or whatever do it in your personal life right um whatever you're doing like maybe you create
like give me the news on this topic of like what's being discussed in like social media
and news and whatever right try and find um a contrarian point of view or like a devil's
advocate point of view just so another thing i like doing is you know with news and social
media we're so in our bubbles and it's so hard to get out of those bubbles actually if you
actively ask ai to take you out of that bubble what is the opposing point of view it does it
quite well and you can kind of try and break some of those walls a little bit it's not an
automation but i think it's really useful for how we see the world and how we think about
things yeah i am you know i've noticed i was looking for like recipes for breakfast
on instagram right and then my discovery page was just full of food like all of it
um and it's like i mean i don't i don't really want to see you know just that so i think you
you definitely get into that like single mindset of um of just seeing like one thing
or two things so yeah um so final question um if you could like share one message to
every every person that's sitting in a company right now wondering whether ai is going to make
them more valuable or it's going to make them redundant what would be that message if you if
a majority of your role is doing things that ai and by ai really mean llms right does really
well as well you're probably in the danger zone right so if your role is coordinating information
finding uh like reading through things to like find information summarizing things
you're in danger zone um and it doesn't necessarily mean you're going to be out in a year focus on
hopefully your role has some other aspects focus on those right um so even like even if you're
doing mostly let's say you like find insights from like different reports and you combine them
into something else right or you're doing marketing like content creation right like
super prime for automation you can then use your judgment and your intuition that you've
developed over the years to guide the the ai and the machine like how you should be doing
and where your values lie and so there's ways that you can kind of spin it um but then the
other thing i would say just because you're doing it doesn't mean you're going to be kept
you know the the game of corporate politics is visibility so you know you have to play the game
so be really really loud about all the things you're doing that machines can't do
yeah i think that's that's a really good advice um if um if someone wanted to to work
with with you and and you know their company uh how uh how should they get in touch
yeah um i'm on linkedin um you can dm me or alex at hawker.ai okay thank you so much
thank you so much for having me`,

  "the-9-to-5-is-changing-how-to-become-the-ceo-of-your-career-with-ai": `My guest today has built people functions in over 30 countries,
scaled five companies from the ground up, helped raise over 200 million in funding,
and taken a company all the way to the NASDAQ. She has done all of this not as a founder,
not as a CEO, but as the person that founders and CEOs quietly rely on more than anyone else
in the building. She is a psychologist, an executive coach, and someone who has spent 25 years
sitting with people at their most honest, in the moments that actually define a company's culture.
She has won global awards for mental health strategy, built workplaces that rank among the
most loved in the world, and traveled to over 100 countries. She know around her own
consultancy and coaches some of the most senior leaders in tech. Kelly Hartman, welcome to Womenlead AI.
So Kelly, welcome to Womenlead AI podcast. Thank you so much for your time and for coming
on here. Really excited. Yeah, of course. Me too. You're a psychologist by training and you spent
like the past 25 years inside various organizations watching how people respond to change. I would
say probably AI is the biggest change that is happening right now. What does your psychology
background tell you about why so many people are resisting that change? So I think it's really
important to know and I have this whole philosophy that there's no one-size-fits-all. So there are
a lot of people resisting it, but there are also a lot of people embracing that. And I think
that's really important to know because irrespective of your age, your gender, where you are in
the world, what role you play in the organization, you are going to get different types of approaches
and how people respond to this. Why I think in just from a psychological or even just a human
point of view, people resist change when it's unknown to them. When people are afraid of the
unknown, it's different. Even in life, people like sometimes their comforts, they like to have
a routine and this throws everything out. So I think one of it is the unknown. I think another
aspect is that they're seeing in the media that people are losing jobs. And maybe part of that
is because of AI, but I don't really believe that completely. I believe part of it is people
just have overspent on headcount or that they're getting rid of underperformers, not saying that
everyone that, you know, I want to put that as a big caveat. If someone is exited from an
organization, they've used AI as the reason why. I'm not saying everyone's underperformed,
but sometimes those departments maybe are not needed or they've overspent and things like that.
So I think the fear of the unknown, I think what the media and especially social media,
which is at our fingertips these days and you see all the headlines, 10,000 people lose jobs
because of AI. And I think that scares a lot of people, right? Yeah, I think I did hear on another
podcast where they were saying like, actually a lot of companies, you know, they hired so many
people during COVID and now they don't need them anymore and kind of normal sort of economy.
So they're just using AI as this kind of thing that they can put a blame on and yeah,
a lot of it comes from that. I was at also a panel the other day, it was all on AI. It was
really interesting and you had people, CPOs, you also had like board members of the AI
governance in finance and just people from, you know, broadcasting studios and just
CEOs and, you know, the conversation was had like and I think that is scaring people the most,
you know? What was the, do you want to tell me more about the, it was a conference?
It was like a, no, it was a panel. And yeah, it was a panel and it was, I really enjoyed it.
Like, you know, I think there was diverse views. There were some people that think it's
all hype and there were others that don't and that actually believe that, you know, we've
got an embraces. You know, same as many things that, you know, I came from the age when we,
you know, computers came later. Like, you know, we didn't grow up with computers. We didn't have
phones at our fingertips. I think I'm seeing a lot on the Instagram like reels about what
it was like growing up in the 80s and 90s. That's me, you know? And so we didn't have
all of that at our fingertips. But I think, you know, even my father who's 76,
like he asked me to do stuff with AI, like more of the, you know, perplexity or Claude and things
like that. Because I've traveled so much and my whole life has been out of my comfort zone,
getting up and living across the different sides of the world. Like I'm one of those that is
curious and will try. I am not great in tech. Like tech isn't my, you know, but it helps me
do my job so much easier. So I think those that embrace it and are curious and want to
learn what it's about, will use it and utilize it. And others are more afraid and won't even try
different things. And so a lot of it is a mindset and a lot of it is, is, and I really believe a lot
is mindset. Yeah, I 100% agree. And I think when we think about like any technology coming
on onto the market, you know, you can be in the camp of like, oh, like this is going to
destroy jobs, like it's, it's, you know, all doom and gloom. And then, or you can be in the camp,
like, oh, this is the biggest opportunity that, you know, has ever been in my lifetime. Like,
I'm going to find a way to make use of it. So, you know, and the doom and gloom,
like it doesn't help you, I don't think it helps you in any way. So if you embrace it and,
you know, if let's say you are the, you know, the best person that knows this particular thing,
like you can really position yourself as like an expert. So of course, and you can learn and you
can grow yourself. And I think inherent in my nature, I'm not a doom and gloom person. I've
always been maybe overly optimistic. I know I mentioned to you before that I'm listening to
a lot of Derek Grant at the moment, which is things come within you, like you, you know,
and I'm very much that we're accountable for everything that happens in our life, bad or good,
right? Like if I take accountability for things, even the shitty stuff that goes wrong in my life,
I'm free. I'm more powerful in that. And I think the same is with AI, right? You know,
when I first heard of it, I was like, so curious, what is this? You know, it started
with chat GPT originally, but I've also like perplexity. I've had Claude for a while, like,
and then AI, I mean, we were using AI in so many different ways and machine learning and data science
and, you know, and I see it as an opportunity. Like for me, I just did a big proposal for a
broadcasting studio for a TV series, like straight out, not it's not inherent in my
CPRL, but I'm also a creative like I'm working for a major rap artist at the moment. And in the
proposal I was doing with his organization, I used Claude to help me put a presentation together
that would have taken me weeks because it's so fiddly and I can't put stuff together and design
work and videos and it made my life easier so I could get creative about what I want to do.
And if people see it as actually, it's going to make my life more enriching and I'm going to
outsource some of the stuff that I didn't love. My boyfriend, he codes, right? He also runs
implementations for big companies and, you know, I talked to him and I'm like,
customers still want a from person to talk to them through implementation and changes,
but he's learning different things on the weekends to help skill him up on how to
utilize the AI better, right? So yeah, you might not need the same type of engineering,
it may change, but you need to be able to change with that or find something else that you really
want to do. So let's say that, you know, someone is, they have like quite a big company, they,
you know, they hire the employee about 70, 80 people and they're like, okay, we have chat
to be able to employees, but you know, how do we actually like, how do we actually implement AI
into like our operations? And like, what mistakes do you see companies do as well while they go
for that change? So I think being really honest about things, about what you're using AI for,
like challenging people to see how they can use AI to make their jobs more enriching or faster or
do different things like to outsource the work that, you know, actually it's taking you so
much time to do. So I think being open, having a strategy around it to bringing people along
with it and going through a change management process, like, you know, we started, well,
the engineering was using a different type of AI than we were, you know, for some of their work.
As an organisation, we use Glean across the organisation and we had workshops with
everyone that was invited and then it started off with the senior leaders first and the exec
and then the people leaders and then bringing everyone on the journey. And I think
that's some mistakes that I hear people aren't making, you know, like people are bringing in
in too late or they're not encouraging that or they're not having AI as part of their whole
strategy. So each department at our previous organisation spoke to, you know, an expert in
AI to see how we could better use AI in our functions. And that means people are brought
along that journey and then you're not scared of it because we're encouraged to use it. And I think
that's you've got to be transparent about that. And how do you think how much responsibility lies
on the leadership team to drive this versus employees wanting to, you know, trying to drive
the change and implementing it into their like processes? I think a lot has to rest with
you as an individual, like we're in charge of our own careers. I run a program being the CEO of
your career and that is, I've been running that for 20, 25 years in different various ways, but
you're in control at the end of the day. Like I can't blame my organisation because I have an
upskilled or I'm not learning or I'm not curious. Like you've got to have the grit,
the ownership that, you know, goes back to ownership accountability. So yes, it's a
responsibility for leadership, but I'm not going to outsource that responsibility ever. Like I'm in
charge of my own career. I'm in charge of my growth, my learning. And I think my big thing is a mindset,
circle of influence, circle of control. AI is here, right? Like your last of human freedom,
which is Victor Frankel, I don't know if you know who he is. I follow a lot from him because
last of human freedoms is the way you're going to respond to anything. So it goes back,
you can resist it, you can say, I don't want to get involved, like I'm scared,
or you can choose to say, actually, I need to understand everything about it. There are so much,
there's so much free stuff online, there's stuff that you can pay for.
I choose to pay for my subscriptions to stuff because I want the pro versions and I want to
learn myself. So I think everyone has that responsibility in life, right? It's the same
with anything in life, like you choose on how you respond to a situation. Rather than life happens
to you, I'd rather be the driver of every aspect of my life, my relationships, my work, AI, you know?
Yeah, I think, you know, there is some, for example, someone is in their organization
where they're not like using AI or it's not encouraged by the company. Like what I would
say to them is why don't you try to use it in your own personal life? I see so many examples with
members of my family where my dad is constantly using voice mode for just so many use cases
and thinking about like, oh, this is, I don't know, grocery shopping, let's say, this is a process
I do manually. Is there a way that like I can get Claude Cote to do it for me? And yeah, it comes back
to that like feeling like you are the owner of your own journey, right? I started using it before
it was like even spoken about in organizations because I'd heard it and I was like, what is
this thing? And I was so curious about it. And then you have to decide to like, you know,
people are saying, well, people aren't as creative anymore because it writes all your emails and that
but you have to drive that. Like I use it to write LinkedIn posts, not my whole LinkedIn post,
I write it. And then because I have ADHD and a bit of dyslexia, I make a lot of mistakes,
grammar. So it was like, I would get someone to check it all the time. So instead I get,
you know, but then I'll say, no, I want Kelly's stuff and you have to change it back,
you know, so you've got control of it. I also used to write a lot of poems like that was my
favorite thing and it would take me a while but I loved it for friends, birthdays, give speeches.
I could put it into to Claude and it could give me a great poem just but I
can put in all the details, but I don't want to do that because I still want to use my
creativity. So you again have control over that, right? Like you have control. I wouldn't say,
hey, just like I can tell when people are writing me constant LinkedIn messages and posts that are
all through to, you know, an AI tool but I craft it and then ask them to maybe streamline or make
it more concise and then, but sometimes I go back about 50 times, like, you're not getting it right.
Like this is what I need. Actually, this is not my voice. You know my voice. I'm an
Aussie and I speak directly and, you know, and so it's almost like you're, you're constantly
getting to the version you want and it's more like a grammar thing for me, I say.
Yeah, I think there is a balance but I think is, you know, especially when we think about
creative jobs, it feels like, you know, a lot of people are almost outsourcing their creativity
to AI and I wonder, like, where is that balance between having the ownership over idea or, you
know, having that idea be almost owned by AI? What do you think about that?
Yeah, I think for me, like I want ownership of my creative ideas and I want them to enhance it.
Other people want to outsource the whole thing, you know, and sometimes you see a lot on
LinkedIn these days, like, I'm tired of, like, LinkedIn replies automatic, you know, through AI
and things like that. Like, if you're annoyed by it, don't read it. Like, I don't want to get upset by
people's posts or, again, choose what you want to affect you. So I think it's up to the
individual. Like, I'm not going to tell you where you should use AI or not. I know to get the
best out of me. I am a creative person, so I want my ideas. I just want them a bit more polished
sometimes. Or maybe I don't. Maybe I read and go, actually, nah, I can't do this. I'm going to go back
to my own. But I know there are a lot of jobs. Like, for like, I know there was roles like
heads. I remember I had a role once at Deutsche Bank. It didn't last long in that role because
they wanted me as the head of PowerPoint presentations for the XCO, like the worst
role for me ever. I'd never forget this. And they're like, Kelly, but you're working
with all the XCO and I'm like, I don't care. Like, I'm more talent people. But it would take me so long
to do a PowerPoint presentation. Like, you know, but some there are jobs like that. But now,
I suppose those jobs have changed a bit because I could do my, you know, PowerPoint presentations
all on AI. And I love it. It's like that for me is like incredible. And I did one recently,
but we had to go back and perfect it and change it and change different things and do our own
diagrams. But yeah, I can make logos and do a lot of things for you, you know. But
my sister-in-law is a graphic designer and she still designed stuff for me too. But
yeah, I think there's just different versions of it.
You know, you worked with a lot of companies and also worked in a lot of companies where
you're building the company culture or you're a part of that. And when AI starts changing,
you know, how people do work, do their tasks, do their role, what do leaders need to, you know,
keep in mind in order to make sure that, you know, that culture is still there, the one that they
want. You still need to connect with people. You still need to talk to people. You need to
hold people accountable. You need to help, yeah, giving learning opportunities. Like again,
it goes back to empowerment and being honest. I would never outsource that to AI. You know what I
mean? Like there's a lot of stuff where training is delivered by AI. You know, interviews are done
all by AI. Like I think you can do aspects of it, but you still need the human element of
checking in and talking and team meetings and or one-on-ones. Like how often you want to
do them depends on that individual. So I don't think, I think this, you still need to help drive
the culture on the behaviors that you do tolerate and those that you don't and that can't be outsourced
to AI, you know? We're not firing the managers yet. No, I don't think so. Maybe some companies
will. Maybe their whole, you know, their whole managers will be robots or, you know, like,
I don't know, everyone's different, right? That wouldn't be for me because I love
I love that connection. But, you know, they were talking about actually at the panel that a lot
of the roles that are available that they need are in carers and things like that, but people
don't want to do them because sometimes it's not paying well or, you know, from a status point
of view where I've actually, as I've grown and, you know, as I'm getting older, I love
those type of roles that I maybe didn't want to do beforehand, like the caring and being with people
and things like that. Like that gives me a lot in my life. Yeah, it's, I think that, you know,
like future of roles is like such a big thing and yeah, like I do think there are roles right
now, which I'm not going to, you know, I'm not going to be in the some of them will not
change, but then some of them will not exist. And, you know, that's
And you have to be, you've acknowledged that, like they're not going to exist. So what am I going
to do to upskill or change in my way? You know? Yeah. And what, like, tools or workflows have
you adopted in your work and in your life that, you know, really changed, you know,
changed the game for you. Let's call it. Definitely. Claude co and perplexity has
changed everything. Glean changed a bit in our organization because you could search for stuff,
but there's AI built into everything. HTS, you know, engagement tools, payroll,
banking, like it's, it's everywhere, but what's changed for me in my life is perplexity, Claude,
Claude. How do you use them? A lot for writing presentations, spreadsheets.
While I was writing interview notes, I, my, my writing is so terrible. I couldn't understand
anything. People would say, Kelly, what do you say? But I learned to write straight in was
while I was interviewing candidates. And then I could put in the best summaries ever, you know,
like it JD's, you know, benchmarking data, everything could, could be used with AI these days.
Leadership training in development, like I would build it, but I don't, I'm not one for big,
like PowerPoint presentations for leadership training. I'm about conversations, you know,
but yeah, there's so much, you know, it helped me be a lot quicker in getting stuff right. Like,
have you tried like whisper flow or any of those where you can say what you want and
it helps you with like writing it down, actually. No. It's really good. Okay, I've got to try that
one. Especially like if you are someone that struggles with like writing like the correct
kind of the spelling of the words. And people also speak so much quicker than they are able
to write down. So once you try it, you're like, oh, I'm not typing this. No, I'm not typing
it anymore. Oh, I have used versions of that to be, to be really fair. Yeah. Yeah. But I can use
that on Claude and that as well. Like all I do is just the voice mode. Yeah. Sorry. I use it all
the time. That is good. Yeah. And that can interpret me because I'm one to leave voicemails.
If anyone knows me, I'll leave a voicemail on WhatsApp because I make so many spelling
mistakes and no one understands what I'm saying. Like even my parents like Kelly,
what are you trying to tell me? And so it's perfect. But even images, I even did a vision
board the other day. I'd created my own ages ago. And then, you know, sometimes we've done stuff
in workshops and things like that. And I did it using AI. It was great. I have like friends who
either they laugh or hate their voicemail switch. I never see people that are in between,
oh, it's okay. No, it's either like, oh, this is all I use or I absolutely hate using it.
And when I when I moved to Spain for a year, everyone would use voice messages to that
point where they would use it in a like a group chat, which I thought was wild.
Especially the Spanish would do it. It goes on in cultures too, doesn't it?
Yeah. But it's, I love them. So I'll leave you some, but everyone knows that I'm going to leave.
Like my CEOs are always like, Kelly, we love it. We love a Kelly voicemail. But I,
I think I press on and it doesn't record at the beginning. So they always miss a start.
And they're like, Kelly, who are you talking about? What are you talking about? So yeah,
I, it's a life changer for me too. That's awesome. Yeah. And when we, you know, like
recently I saw this research which showed that women are adopting AI at 25% lower rate than men.
What, why is your read on that from a lens of someone who, who studies psychology?
Why is there not a big adoption among women? Yeah, I don't think it's a capability gap at
all, as we've seen. Maybe just more of a scarcity gap or less people being part of the
initial conversations or different priorities at the moment. But, you know, a lot of the women
I know are using it all the time. So yeah, it depends on what roles they play, maybe,
maybe not in the right conversations at the, at the right times, you know, there's less that,
yeah. I think it really depends on the kind of community that you're in. Because, you know,
it's like you will have community around you and everyone will use it. And then, you know,
there are those, I think silos in between like different people who, who want to use it.
And where they're located, cultures, what they're doing, like it all depends on so many different
factors, right? What would you say to someone like, I, I hear the news about, you know, a new AI tool
being coming out every, like every other day. How, how do you deal with that with the, you know,
that train constantly moving and having to like, keep up with it?
I think, like, again, it goes back to your mindset and behaviors and what you can control. Don't
get overwhelmed. Like, I don't look at every single tool cut because I see it all this,
you need to do this class and you need to do this and that, like, do your own research,
you know, listen to referrals. You've just given me one today and do what you can do, you know,
like, you know, and, and I think that's the most important, like research what is out there.
Go beyond chat GTP because I think there's so many other different things. But AI, I think,
because it is used so much, it's in so much of our life already, right? Like AI in maybe on,
on your Netflix or your Instagram or whatever you're using that AI is built into that. So I think,
you know, spend like everyone is different. Some people might want to spend 15 minutes a day. Some
people may be half an hour. You probably three or four hours a day. Like, it depends on what
your passion is. But find out, like, what interests you, you know, there's AI in videos,
if you want to be a podcast, you know, podcast, like, look at the different tools that
are using for AI. I use it for, you know, HR. I'll be looking at AI and HR to see or in my
creative fields that I'm doing. Yeah. And when I think about like your journey, you work with a
number of like really large companies. And then you have, you know, started your own company.
What made you to decide that kind of like leap to, to go on your own?
I think just sometimes being aligned to, to, to what I want in life too, like I've had quite a few
incredible opportunities that have come my way just by being real and saying still for a bit.
Like I always think I need to chase a big, next big thing, next big title, next big organization.
Who do I want to work with? Like the big names. And then I realize I need to sit
in the reality of what, what fuels my soul at the moment. And I feel like I've been given opportunities
that not that I, like anyone that knows me would go so you Kelly. Like my passion is,
like I love travel, traveled over a hundred countries. I love people that are making a
difference. I'm very big into healthcare, education, like I've been in fintech and
things like that. I just want to help people. But who knows? I, you know, I'm interviewing
for companies at the moment. I could go join another one if, if it is aligned to what I want.
And I always have a lot on the side at the moment. And, and so I feel like that people need to do
what is aligned to them all the time and take a risk, you know, know that you may fail,
know that you may fail five million times, you know, like I did a bit of work. And then I
was like, actually, I wanted to go back into being a team. Like I do miss that teamwork.
And I think that's really important for me. And so I think it's about being fluid and open to those
opportunities, right? And I think they say so many people say these days that, you know,
some people believe that the nine to five is over. And that, you know, at the moment for
last year, like I've been traveling on so many different projects and I love my life at the
moment, you know, and, but I'll always love my life because I want, I've always wanted to
create a life that I didn't need a holiday from. So I'm passionate about what I do,
whether it is in a corporate, a startup, you know, a non-for-profit, or I'm doing my own thing
with my projects. I really believe that I'm just aligning to, to, to myself.
Yeah. And what, what did you see as like the biggest thing that you've learned while, like,
because you're now, you have, you're the founder of your company versus something that
you wouldn't have been able to learn working for someone else.
For me, because I'm not in sales, you have to do your own business development and things like
that, which is different. But I don't really, I think a lot of my work has come with referrals
or a casual conversation, or you meet someone said you should meet this person and things
like that. So I think, I think that the unknown, like you don't know, you know,
paychecks, you know, you might get a huge amount for one project, something else could come along,
and then you might not have anything. And you've got to sit on the, you know,
the discomfort of that, of not knowing when your next paycheck is, is coming, or you're
going to get a big one and then nothing for a while. Also be someone with ADHD, like,
to keep motivated all the time too, like self-discipline, which I do believe I have because
I'm the, you know, I go to the gym a few times a day and, you know, but I can get sidetracked by
stuff. And yeah, focus on the stuff that I love rather than the admin stuff, like I'm not good.
I don't really enjoy the admin side of everything.
Yeah. And how, you know, when it comes to AI education, I feel like it has to be
a constant thing that you're doing because the tools, you don't have to, you know,
keep up with every tool, but you have to be continuously finding out, like, what is new,
how can I use it to, you know, to my advantage, to improve my productivity.
But how do you keep yourself, you know, kind of disciplined to do that and to invest in,
like, education in that way?
I think, again, like, it goes back to mindset. You either have to, like,
if you know that you're not disciplined in those ways, you need to set yourself a target each day
or whatever. Everyone's disciplined in each, in each way. Like, I believe that I am self-disciplined
in a lot, like, you know, in, and I think that comes from, you know, healthy eating and,
and, and gym and, and everything I want in life, like, you have to go do it yourself.
Like, there's support around you. But I think it is also using your support system. Like, you know,
I'm having a bad day. I'm not really focused today. And giving yourself a bit of grace for that.
Like, sometimes I feel like, oh my God, I haven't done anything today. You know,
I've just been to the gym. I've done a few things, reached out to a few people,
and that's okay too. Like, you know, to, to have that rested in between. But I think,
I think those things do come from within. Like, you know, I'm listening to podcasts
at the moment that are getting me into that mindset, you know, that's the on the streak,
you know, and I think you can go off track for a while in, and you can wallow in something
that doesn't work out. And if something fails, like, you've got to get back and start,
you know, you've got to, you've got to get back and do it again, you know.
Yeah, I think I was, I was just telling you when we first met that I had,
I completed a hundred Pilato sessions. Yes. I'm so proud.
I'm very proud of myself for doing that. But you know, I did find it, I mean,
the reason why I like started and go to these sessions is also because like,
once it is scheduled, you like, you just go and you can't cancel it 12 hours before.
So. Yeah, we should pay, right? Oh, you have to pay, yeah. So, you know, the additional 10 pounds
that you have to pay actually really help with your discipline. So, you know, maybe that's the
that's the push that some people need to like, you know, money in the jar, if you don't do
something that you say, yeah, there are different ones I used to do. I can't have this unless
I finish that couldn't watch this TV show or, you know, can't go to, yeah, whatever it is.
So, yeah, I think a lot of people, like you do have self-discipline, but I've,
I've got self-discipline, but I've got a lot of friends go Cal. I don't know how you do it.
Like, you know, you're so disciplined, but yeah, I constantly want to learn. Like,
I constantly my whole life is being out of my comfort zone. Like, if you think of
even when I first traveled, I was so scared to go by myself. I cried. I said, Dad,
what happens if my friends don't meet me? It was to the Greek islands. I'm Australian.
So, it was far away. It's not like a four-hour trip. And then I'm like, what's worse that can
happen? And now, like, I've been Africa, South America all over Europe, like Central America,
all by myself. And even recently, I did it again. My comfort zone is a lot bigger now,
because, you know, I keep on doing stuff that pushes me the next level, you know?
And you've traveled to a hundred countries, which is wild. When I think about it, what, you know,
what that experience allows you to understand more, like, about people, about cultures,
and also as we go into the future, how AI is going to change that, like, that future.
Mm-hmm. I think everyone is different, right? There are so many different cultures. It gives
me greater understanding in the world of different people, different religions,
different circumstances to be resilient. Not everything is going to go your way. You're
not going to understand certain things. There's different ways that some people may
be shocked that you behave in a certain way, or you can't do something in,
in different cultures. Some cultures are dangerous, you know? Like, there are, you know,
I've been in situations where, you know, it's dangerous. Sometimes, you know,
walls have broken out. I've had that, uprisings. You have to stay confident in who you are. You
have to have your wits about you. You've to sense the situation, and if it's not comfortable,
get out. I still believe generosity and kindness, like being open to every single
conversation. Like, some people are like, you're so trusting, you're so nice to people, but
I love, like, I love every conversation I have. And yeah, it's told me to stand up on my own. Like,
I'm okay going to, I'm okay traveling by myself, and obviously I'm okay having a meal
by myself or going, and I've had the most amazing connections. I've got friends all
over the world now, you know, and experiences that you could never, ever buy. Like, my whole
life is experiences. I, I'm not, I'm not big on things. Like, I don't need a big house or car
or things like that. I feel like I'm rich with experiences. So AI will never replace all of
that. It might make things easier for like, travel and banking. Like, when I traveled,
we didn't have a phone. Like, if I got lost, I was lost all day. There's no,
I rang my parents' reverse charges and cost them a fortune from Australia, I remember,
from Europe, all things like that. Like, you know, and I love those days, you know,
I think everyone's on their phones taking selfies and this and that, and it's changed the way from,
from, from where I used to travel. And Bali has changed. I used to go, I went to Bali,
you know, 30 years ago, there was nothing there, you know what I mean? No, yeah,
Hali, any hotels or anything. So I feel blessed for some of the experiences and I want to
still try to go. And I don't think AI can change that, but like I said, AI changes that the way you,
you travel, you book hotels, you can, you know, I did go and knock on doors to find
places to stay or order food if you arrive late or, you know, yeah, different things.
One of those, yeah. You know, when you think about the future, what do you think
the organizations and individuals like who's going to come out of the AI change
stronger and what do they think they will do differently to people that want?
Be open, be curious, embrace it, a good change management. You need to bring people along the
journey with everything. And if, if you leave your people behind in an organization, I don't
think they're going to come out as strong, offer it up for people like, you know,
offer pro licenses, including in your tooling when you're onboarding, including in your
induction program, like have challenges around AI and what you can do to better improve
whether it's people processes or processes within the organization, operations, engineering,
finance. And let's say five years, you know, you, you have worked in
on creating places that are genuinely loved by employees. I think one of the places that you
worked in, it was the best place to work, wasn't it? Most loved workplace. What does
a most loved workplace look like in five years time in a work where AI, well,
I imagine it will be embedded in everything that, you know, we touch and interact with.
So making sure that your jobs are enriching and they're empowering and that you're doing
great work and having AI make your job more enriching in some way, you know, to, to that,
that's, and I think still like, you know, the, the connection, the honesty, the transparency
is still just as important, like where people can be themselves and they're empowered to, to do
work, to, to, to learn and to grow and develop in different ways. Yeah. No, 100%. Is there anything
that I haven't asked you that you would like to talk about? What is your favorite AI tool that
you're using at the moment? So cloud code. I, so there's, you can use it on your desktop through
the, you can use it through browser or you can install it on the computer. But when you use it
with this app like Antigravity, it's absolutely amazing because then you can have like 10
windows open and you can do different queries and it will be able to do all of these projects
at the same time. So it feels like you're just like, it feels like you have that superpower where
you just, you know, give that task and then another one, another one, another one, and then
you just go back to window number one and see, okay, this is, this is done. So I, yeah, I love that.
The fact that with cloud code as well, you can, you can like create a presentation,
which is something that you said you worked on in your own like brand colors as well,
which to me is, yeah, it's, it's wild, but it can do that. Yeah. And then just the imagery and,
you know, the, the logos of photos, like, you know, films, everything, it is great, you know,
it's amazing. Like, so that's why I tell people like just, you know, if my 76 year old parents
can use AI, they're using it for so much and they're asking me, what do you think of this and,
you know, and anyone can, like honestly. So let's do a fast round. Okay. So what's the one
thing that AI will never replace about a great people either? I think compassion and empathy
understanding and just deep connection. What's the sign that a company has a healthy culture?
Like, you know, you walk into the company and you're like, oh yeah, they have like great culture.
That I can be myself and not judge for that. Like, yeah, that's for me, you know, and then I
can be honest and truthful and not cut down. When, what's a place you haven't traveled to
and you would love to travel to? Madagascar. Oh, wow. Yeah. And what's your,
what's your favorite place you've traveled to? That's a hard one because there's so many.
There's no top free. Brazil. Okay. I love Brazil. That was one of my favorite places.
I love Tanzania. Italy is our favorite. We go and Iceland. Oh my god. Iceland is beautiful.
That's amazing. Yeah. I've been to Italy out of those four you mentioned. So
there's still on my list. Yeah. Sometimes I think I should just, you know,
maybe do travel agent. Someone was asking me the other day if I could help her daughter because
she wants to go to Europe by herself and so many people come to me. So yeah,
enable women to travel alone. That's amazing. So if someone wanted to,
you know, get in touch with you and get your help, how, how should I do that?
Oh yeah, they can just contact me on LinkedIn. Kell Hartman, Kelly Hartman at LinkedIn.
Well, we'll put your link in there. Yeah, for sure. Well, thank you so much. And yeah,
it was, it was great talking to you. Yeah, it was so beautiful. Thank you for having me on
your podcast. Before you go, one thing, if today's episode sparks something for you
and you want to take that further, Women Lead AI runs a monthly AI learning lab
where we go hands on with tools, trends and real use cases together as a community.
There is no jargon, no gatekeeping, just women helping each other get generally good at AI.
Link is in the show notes and see you next time.`,
};
